name: Call subordinate
on:
  workflow_dispatch:
    inputs:
      cluster_tier:
        description: "Select cluster tier"
        required: true
        type: choice
        default: PAID
        options:
          - PAID
          - FREE
      base_version:
        description: "Provide Base DB version for upgrade"
        required: true
        type: string
      target_version:
        description: "Provide target DB version to be validated"
        required: true
        type: string

jobs:
  drop:
    runs-on: ubuntu-latest
    steps:
      - name: Still echoes
        run: echo "-${{ inputs.cluster_tier }}- -${{ inputs.base_version }}- -${{ inputs.target_version }}-"
  call:
    uses: ./.github/workflows/main.yaml
    with:
      cluster_tier: ${{ github.event.inputs.cluster_tier }}
      base_version: ${{ github.event.inputs.base_version }}
      target_version: ${{ github.event.inputs.target_version }}
